### ISSUE TITLE
(FunctionClauseError) no function clause matching in Readability.Helper.remove_tag/2

### ISSUE THREAD

**Issue by edevil** [keepcosmos/readability#30]
```
iex(2)> Readability.summarize("https://www.wired.com/2016/10/review-logitech-keys-go/")
** (FunctionClauseError) no function clause matching in Readability.Helper.remove_tag/2

    The following arguments were given to Readability.Helper.remove_tag/2:

        # 1
        {"echo", "echo"}

        # 2
        #Function<0.78353828/1 in Readability.ArticleBuilder.build/2>

    Attempted function clauses (showing 4 out of 4):

        def remove_tag(content, _) when is_binary(content)
        def remove_tag([], _)
        def remove_tag([h | t], fun)
        def remove_tag({tag, attrs, inner_tree} = html_tree, fun)

    (readability) lib/readability/helper.ex:52: Readability.Helper.remove_tag/2
    (readability) lib/readability/helper.ex:55: Readability.Helper.remove_tag/2
    (readability) lib/readability/helper.ex:66: Readability.Helper.remove_tag/2
    (readability) lib/readability/helper.ex:55: Readability.Helper.remove_tag/2
    (readability) lib/readability/helper.ex:66: Readability.Helper.remove_tag/2
    (readability) lib/readability/helper.ex:55: Readability.Helper.remove_tag/2
    (readability) lib/readability/helper.ex:59: Readability.Helper.remove_tag/2
    (readability) lib/readability/helper.ex:66: Readability.Helper.remove_tag/2
    (readability) lib/readability/helper.ex:55: Readability.Helper.remove_tag/2
    (readability) lib/readability/helper.ex:59: Readability.Helper.remove_tag/2
    (readability) lib/readability/helper.ex:66: Readability.Helper.remove_tag/2
    (readability) lib/readability/helper.ex:55: Readability.Helper.remove_tag/2
    (readability) lib/readability/helper.ex:66: Readability.Helper.remove_tag/2
    (readability) lib/readability/helper.ex:55: Readability.Helper.remove_tag/2
    (readability) lib/readability/helper.ex:59: Readability.Helper.remove_tag/2
    (readability) lib/readability/helper.ex:66: Readability.Helper.remove_tag/2
    (readability) lib/readability/helper.ex:55: Readability.Helper.remove_tag/2
    (readability) lib/readability/helper.ex:59: Readability.Helper.remove_tag/2
    (readability) lib/readability/helper.ex:66: Readability.Helper.remove_tag/2
    (readability) lib/readability/helper.ex:55: Readability.Helper.remove_tag/2
```

**Comment by edevil** [comment]
This is probably related to this garbage that appears inside the HTML:
```<? echo esc_html( wired_get_the_byline_name( $related_video ) ); ?>```.

**Comment by keepcosmos** [comment]
Right, Readability can not parse the weird tag (maybe serverside script). It's a bug should be fixed.
